(function (global) {
  'use strict';

  if (!global.SYNO || !global.Vue) return;
  SYNO.namespace('SYNO.ZionReleaseStation');

  var styleId = 'zion-release-station-native-style';
  var styles = [
    '.zion-native{height:100%;box-sizing:border-box;background:#f3f6f9;color:#1f2933;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}',
    '.zion-native *{box-sizing:border-box}',
    '.zion-native-header{display:flex;align-items:center;gap:12px;height:78px;padding:15px 22px;background:#fff;border-bottom:1px solid #dce3ea}',
    '.zion-native-icon{width:44px;height:44px;border-radius:10px;box-shadow:0 4px 12px #203b5a24}.zion-native-title{flex:1}.zion-native-title strong{display:block;font-size:17px;font-weight:650}.zion-native-title span{display:block;margin-top:3px;color:#74808c;font-size:11px}',
    '.zion-native-nav{display:flex;gap:5px;padding:11px 22px;background:#fff;border-bottom:1px solid #e3e8ed}.zion-native-nav button{padding:8px 13px;border:0;border-radius:6px;color:#687582;background:transparent;font:inherit;font-size:12px;cursor:pointer}.zion-native-nav button.active{color:#176fbe;background:#e8f2fc;font-weight:650}',
    '.zion-native-body{height:calc(100% - 125px);overflow:auto;padding:22px 26px}.zion-native-intro{margin-bottom:18px}.zion-native-intro h1{margin:0 0 6px;font-size:22px;font-weight:650}.zion-native-intro p{margin:0;color:#687582;line-height:1.55}',
    '.zion-native-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.zion-native-runtime{grid-column:1/-1}.zion-native-card{padding:17px;background:#fff;border:1px solid #d9e1e8;border-radius:8px;box-shadow:0 2px 7px #1e33420d}.zion-native-card h2{margin:0 0 13px;font-size:14px;font-weight:650}.zion-native-card p{margin:0;color:#687582;font-size:12px;line-height:1.55}',
    '.zion-native-status{display:flex;align-items:center;gap:9px;margin-bottom:11px;font-weight:650}.zion-native-dot{width:9px;height:9px;border-radius:50%;background:#e0a326;box-shadow:0 0 0 4px #e0a3261c}.zion-native-dot.healthy{background:#1aa36f;box-shadow:0 0 0 4px #1aa36f1c}.zion-native-dot.offline{background:#d64b4b;box-shadow:0 0 0 4px #d64b4b1c}',
    '.zion-native-list{margin:0;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0 22px}.zion-native-list div{padding:8px 0;border-top:1px solid #edf0f3}.zion-native-list dt{color:#77828d}.zion-native-list dd{margin:4px 0 0;font-weight:650}.zion-native-services{display:grid;gap:8px;margin:0;padding:0;list-style:none}.zion-native-service{display:flex;align-items:center;gap:8px;padding:8px 0;border-top:1px solid #edf0f3}.zion-native-service b{flex:1;font-weight:600}.zion-native-service small{color:#77828d}.zion-native-service.ok i{color:#159866}.zion-native-service.error i{color:#c84a4a}',
    '.zion-native-form{display:grid;gap:13px}.zion-native-form label{display:grid;gap:5px;color:#35404c;font-size:12px;font-weight:650}.zion-native-form input{width:100%;padding:9px 10px;border:1px solid #cbd4dd;border-radius:6px;color:#20242a;background:#fff;font:inherit;font-size:12px}.zion-native-form small{color:#77828d;font-size:11px;font-weight:400;line-height:1.45}.zion-native-form-message{min-height:18px;color:#687582;font-size:11px}.zion-native-form-message.error{color:#c23e3e}.zion-native-form-message.ok{color:#16845b}',
    '.zion-native-actions{display:flex;gap:8px;margin-top:16px}.zion-native-button{padding:8px 13px;border:1px solid #cbd4dd;border-radius:6px;color:#35404c;background:#fff;font:inherit;font-size:12px;font-weight:650;cursor:pointer}.zion-native-button.primary{border-color:#1677d2;color:#fff;background:#1677d2}.zion-native-button:disabled{opacity:.55;cursor:default}.zion-native-button:hover:not(:disabled){filter:brightness(.97)}',
    '.zion-native-note{padding:12px 14px;border-left:3px solid #1677d2;background:#edf6ff;color:#53606d;font-size:12px;line-height:1.55}.zion-native-note.warning{border-color:#d08a1e;background:#fff8e9}.zion-native-route-state{margin-top:5px}.zion-native-route-state.valid{color:#16845b}.zion-native-route-state.invalid{color:#c23e3e}',
    '@media(max-width:700px){.zion-native-grid{grid-template-columns:1fr}.zion-native-runtime{grid-column:auto}.zion-native-list{grid-template-columns:repeat(2,minmax(0,1fr))}.zion-native-body{padding:18px}}'
  ].join('');

  function installStyles() {
    if (document.getElementById(styleId)) return;
    var style = document.createElement('style');
    style.id = styleId;
    style.textContent = styles;
    document.head.appendChild(style);
  }

  var template = [
    '<v-app-instance class-name="SYNO.ZionReleaseStation.Instance">',
    '  <v-app-window width="980" height="680" ref="appWindow" :resizable="true" syno-id="SYNO.ZionReleaseStation.Window">',
    '    <div class="zion-native">',
    '      <header class="zion-native-header"><img class="zion-native-icon" src="/webman/3rdparty/zion-releasestation/images/app_64.png" alt=""><div class="zion-native-title"><strong>Zion Release Station</strong><span>DSM control center</span></div><button v-if="webAccessEnabled" class="zion-native-button primary" type="button" @click="openWorkspace">Open workspace ↗</button></header>',
    '      <nav class="zion-native-nav" aria-label="Release Station sections"><button type="button" :class="{active: tab === \'overview\'}" @click="tab = \'overview\'">Overview</button><button type="button" :class="{active: tab === \'activation\'}" @click="tab = \'activation\'">Activation</button><button type="button" :class="{active: tab === \'settings\'}" @click="tab = \'settings\'">Configuration</button></nav>',
    '      <section class="zion-native-body">',
    '        <div v-if="tab === \'overview\'"><div class="zion-native-intro"><h1>Release Station control center</h1><p>Monitor the service, review the runtime and configure the workspace directly from DSM.</p></div>',
    '          <div class="zion-native-grid">',
    '            <article class="zion-native-card zion-native-runtime"><h2>Runtime</h2><dl class="zion-native-list"><div><dt>Version</dt><dd>{{ health.version || \'—\' }}</dd></div><div><dt>Platform</dt><dd>{{ health.platform || \'—\' }}</dd></div><div><dt>Database</dt><dd>{{ health.database || \'—\' }}</dd></div><div><dt>API</dt><dd>127.0.0.1:24871</dd></div></dl></article>',
    '            <article class="zion-native-card"><h2>Package health</h2><div class="zion-native-status"><span class="zion-native-dot" :class="healthClass"></span>{{ healthTitle }}</div><p>{{ healthDetail }}</p><div class="zion-native-actions"><button class="zion-native-button" type="button" @click="refreshOverview">Refresh</button></div></article>',
    '            <article class="zion-native-card"><h2>System services</h2><ul class="zion-native-services"><li v-for="service in services" :key="service.id" class="zion-native-service" :class="service.state === \'ready\' ? \'ok\' : \'error\'"><i>{{ service.state === \'ready\' ? \'✓\' : \'!\' }}</i><b>{{ service.label }}</b><small>{{ service.detail }}</small></li><li v-if="!services.length" class="zion-native-service"><small>Loading live service checks…</small></li></ul></article>',
    '            <article class="zion-native-card"><h2>Workspace</h2><div class="zion-native-status"><span class="zion-native-dot" :class="webAccessEnabled ? \'healthy\' : \'offline\'"></span>{{ webAccessEnabled ? \'Workspace enabled\' : \'Workspace disabled\' }}</div><p>Active DSM route: <strong>{{ workspace.active_route || workspace.route || \'/releasestation/\' }}</strong></p><div class="zion-native-actions"><button class="zion-native-button" type="button" @click="tab = \'settings\'">Configure workspace</button></div></article>',
    '          </div></div>',
    '        <div v-else-if="tab === \'activation\'"><div class="zion-native-intro"><h1>Activation</h1><p>Manage the license and entitlement status for this Synology installation.</p></div><article class="zion-native-card"><h2>License connection</h2><div class="zion-native-status"><span class="zion-native-dot"></span>License service not connected</div><p>License activation is kept in the native DSM surface so the deployment workspace remains focused on sites and releases. Connect your Zion license when the licensing endpoint is provisioned for this installation.</p><div class="zion-native-actions"><button class="zion-native-button primary" type="button" disabled>Connect license</button></div><div class="zion-native-note warning" style="margin-top:16px">The license connection endpoint is not provisioned in this build yet. Your local sites and deployments remain available.</div></article></div>',
    '        <div v-else><div class="zion-native-intro"><h1>Workspace configuration</h1><p>Configure how the Release Station workspace is exposed through DSM.</p></div><article class="zion-native-card"><h2>DSM workspace route</h2><form class="zion-native-form" @submit.prevent="saveWorkspace"><label>DSM Route<input v-model.trim="workspaceDraft.route" type="text" inputmode="url" placeholder="/releasestation/" autocomplete="off"><small>Use a unique path beginning with /. Reserved DSM paths, traversal and unsafe characters are rejected.</small><span class="zion-native-route-state" :class="routeValidation.ok ? \'valid\' : \'invalid\'">{{ routeValidation.message }}</span></label><label class="zion-native-toggle"><input type="checkbox" v-model="webAccessEnabled" :disabled="webAccessState === \'saving\'" @change="saveWebAccess"><span><strong>Enable workspace URL</strong><small>Keep the Release Station workspace available through the DSM route.</small></span></label><div class="zion-native-actions"><button class="zion-native-button primary" type="submit" :disabled="workspaceState === \'saving\' || !routeValidation.ok">{{ workspaceState === \'saving\' ? \'Saving…\' : \'Save route\' }}</button><button class="zion-native-button" type="button" @click="refreshOverview">Refresh status</button></div><div class="zion-native-form-message" :class="workspaceMessageClass" role="status">{{ workspaceMessage }}</div></form><div v-if="workspace.requires_reload" class="zion-native-note warning" style="margin-top:16px">The route is saved and validated. DSM currently serves {{ workspace.active_route }}; reload the package nginx resource before using the new route.</div><div v-else class="zion-native-note" style="margin-top:16px">The configured route is active. Release Station stays bound to 127.0.0.1 and is not exposed as a standalone daemon.</div></article><article class="zion-native-card" style="margin-top:14px"><h2>Local service</h2><dl class="zion-native-list"><div><dt>Bind address</dt><dd>127.0.0.1</dd></div><div><dt>Service port</dt><dd>24871</dd></div><div><dt>Database</dt><dd>SQLite</dd></div><div><dt>Package</dt><dd>zion-releasestation</dd></div></dl></article></div>',
    '      </section>',
    '    </div>',
    '  </v-app-window>',
    '</v-app-instance>'
  ].join('');

  SYNO.ZionReleaseStation.Instance = Vue.extend({
    template: template,
    data: function () { return { tab: 'overview', health: {}, healthState: 'checking', metrics: {}, services: [], webAccessEnabled: true, webAccessState: 'loading', workspace: { route: '/releasestation/', active_route: '/releasestation/', requires_reload: false }, workspaceDraft: { route: '/releasestation/' }, workspaceState: 'idle', workspaceMessage: '' }; },
    computed: {
      healthClass: function () { return this.healthState; },
      healthTitle: function () { return this.healthState === 'healthy' ? 'Release Station is healthy' : this.healthState === 'offline' ? 'Release Station is unavailable' : 'Checking package health'; },
      healthDetail: function () { return this.healthState === 'healthy' ? 'The local API and SQLite database are ready.' : 'Connect to the local Release Station service to inspect package status.'; },
      routeValidation: function () { var route = String(this.workspaceDraft.route || '').trim(); if (!/^\/[A-Za-z0-9][A-Za-z0-9/_-]*\/?$/.test(route)) return { ok: false, message: 'Enter a valid DSM route, for example /releasestation/.' }; if (route.indexOf('..') >= 0 || /^\/(api|webapi|webman|dsm|file|packagecenter)(\/|$)/i.test(route)) return { ok: false, message: 'This route conflicts with a reserved DSM path.' }; return { ok: true, message: 'Route format is valid.' }; },
      workspaceMessageClass: function () { return this.workspaceState === 'error' ? 'error' : this.workspaceState === 'saved' ? 'ok' : ''; }
    },
    mounted: function () { installStyles(); this.refreshOverview(); this.loadWorkspace(); },
    methods: {
      openWorkspace: function () { if (!this.webAccessEnabled) return; window.open((this.workspace.route || '/releasestation/'), '_blank'); },
      refreshOverview: function () { this.checkHealth(); this.loadMetrics(); this.loadWebAccess(); },
      checkHealth: function () { var self = this; self.healthState = 'checking'; fetch('/releasestation/api/v1/system/health', { headers: { Accept: 'application/json' } }).then(function (response) { if (!response.ok) throw new Error('health'); return response.json(); }).then(function (payload) { self.health = payload.data || {}; self.healthState = 'healthy'; }).catch(function () { self.health = {}; self.healthState = 'offline'; }); },
      loadMetrics: function () { var self = this; fetch('/releasestation/api/v1/system/metrics', { headers: { Accept: 'application/json' } }).then(function (response) { if (!response.ok) throw new Error('metrics'); return response.json(); }).then(function (payload) { self.metrics = payload.data || {}; self.services = self.metrics.services || []; }).catch(function () { self.services = []; }); },
      loadWebAccess: function () { var self = this; fetch('/releasestation/api/v1/settings/web-access', { headers: { Accept: 'application/json' } }).then(function (response) { if (!response.ok) throw new Error('access'); return response.json(); }).then(function (payload) { self.webAccessEnabled = Boolean(payload.data && payload.data.enabled); self.webAccessState = 'saved'; }).catch(function () { self.webAccessState = 'error'; }); },
      saveWebAccess: function () { var self = this; self.webAccessState = 'saving'; fetch('/releasestation/api/v1/settings/web-access', { method: 'PUT', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled: self.webAccessEnabled }) }).then(function (response) { if (!response.ok) throw new Error('access'); return response.json(); }).then(function (payload) { self.webAccessEnabled = Boolean(payload.data && payload.data.enabled); self.webAccessState = 'saved'; }).catch(function () { self.webAccessEnabled = !self.webAccessEnabled; self.webAccessState = 'error'; }); },
      loadWorkspace: function () { var self = this; fetch('/releasestation/api/v1/settings/workspace', { headers: { Accept: 'application/json' } }).then(function (response) { if (!response.ok) throw new Error('workspace'); return response.json(); }).then(function (payload) { self.workspace = payload.data || self.workspace; self.workspaceDraft.route = self.workspace.route || '/releasestation/'; }).catch(function () { self.workspaceMessage = 'Unable to read workspace settings.'; self.workspaceState = 'error'; }); },
      saveWorkspace: function () { var self = this; if (!self.routeValidation.ok) return; self.workspaceState = 'saving'; self.workspaceMessage = ''; fetch('/releasestation/api/v1/settings/workspace', { method: 'PUT', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ route: self.workspaceDraft.route }) }).then(function (response) { return response.json().then(function (payload) { if (!response.ok) throw new Error((payload.error && payload.error.message) || 'DSM Route could not be saved.'); return payload; }); }).then(function (payload) { self.workspace = payload.data || self.workspace; self.workspaceDraft.route = self.workspace.route; self.workspaceState = 'saved'; self.workspaceMessage = self.workspace.requires_reload ? 'Route saved. DSM resource reload is required.' : 'Route saved and active.'; }).catch(function (error) { self.workspaceState = 'error'; self.workspaceMessage = error.message; }); }
    }
  });
})(window);
