ALTER TABLE sites ADD COLUMN custom_framework TEXT;
ALTER TABLE sites ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE sites ADD COLUMN color TEXT NOT NULL DEFAULT '#f28c3b';
ALTER TABLE sites ADD COLUMN push_to_deploy INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN deploy_script TEXT NOT NULL DEFAULT '';
ALTER TABLE sites ADD COLUMN deployment_retention INTEGER NOT NULL DEFAULT 4;
